# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

meanTest <- function(x) {
    .Call(`_impSq_meanTest`, x)
}

medianC <- function(x) {
    .Call(`_impSq_medianC`, x)
}

meanC <- function(x, b = FALSE) {
    .Call(`_impSq_meanC`, x, b)
}

pdistC <- function(x, y) {
    .Call(`_impSq_pdistC`, x, y)
}

normC <- function(v) {
    .Call(`_impSq_normC`, v)
}

rcpp_hello <- function() {
    .Call(`_impSq_rcpp_hello`)
}

